version: '3.9'

volumes:
  mysql-volume:

services:
  laravel:
    container_name: todoapps_laravel
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./back/src/:/var/www
    ports:
        - '8080:8080'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: todoapps_react
    tty: true
    volumes:
    - ./:/app/react
    command: sh -c "cd front  && yarn start"
    ports:
      - ${FRONT_PORT}:3000
  nginx:
    image: nginx
    container_name: todoapps_nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel
      - react
  db:
    container_name: todoapps_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
    - ${DB_PORT}:3306
    depends_on:
      - laravel
  testdb:
    container_name: todoapps_testDB
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${TEST_DB_PORT}:3306
    environment:
      MYSQL_USER: ${DB_USERNAME_TEST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT_TEST}
      MYSQL_DATABASE: ${DB_DATABASE_TEST}
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql